name: Build

on:
  workflow_dispatch:
    inputs:
      publish-release:
        description: 'Push to Nuget'
        type: boolean
        default: false
          
jobs:
  build:
    defaults:
      run:
        shell: bash

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout latest
        uses: actions/checkout@v5
        with:
          submodules: 'recursive'

      - name: Build
        run: dotnet build -c Release
        
      - name: Pack nugets
        run: dotnet pack -c Release --no-build --output nupkgs
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: "Baballonia.OverlaySDK.nupkg"
          path: "nupkgs/*"